// src/utils/NationalityGroups.js

const nationalityGroups = {
    PHILIPPINES: "Philippines",
    ASEAN: {
      BRUNEI: "Brunei",
      CAMBODIA: "Cambodia",
      INDONESIA: "Indonesia",
      LAOS: "Laos",
      MALAYSIA: "Malaysia",
      MYANMAR: "Myanmar",
      SINGAPORE: "Singapore",
      THAILAND: "Thailand",
      VIETNAM: "Vietnam",
    },
    EAST_ASIA: {
      CHINA: "China",
      HONGKONG: "Hong Kong",
      JAPAN: "Japan",
      KOREA: "South Korea",
      TAIWAN: "Taiwan",
    },
    SOUTH_ASIA: {
      BANGLADESH: "Bangladesh",
      INDIA: "India",
      IRAN: "Iran",
      NEPAL: "Nepal",
      PAKISTAN: "Pakistan",
      SRI_LANKA: "Sri Lanka",
    },
    MIDDLE_EAST: {
      BAHRAIN: "Bahrain",
      EGYPT: "Egypt",
      ISRAEL: "Israel",
      JORDAN: "Jordan",
      KUWAIT: "Kuwait",
      SAUDI_ARABIA: "Saudi Arabia",
      UAE: "United Arab Emirates",
    },
    NORTH_AMERICA: {
      CANADA: "Canada",
      MEXICO: "Mexico",
      USA: "United States",
    },
    SOUTH_AMERICA: {
      ARGENTINA: "Argentina",
      BRAZIL: "Brazil",
      COLOMBIA: "Colombia",
      PERU: "Peru",
      VENEZUELA: "Venezuela",
    },
    WESTERN_EUROPE: {
      AUSTRIA: "Austria",
      BELGIUM: "Belgium",
      FRANCE: "France",
      GERMANY: "Germany",
      LUXEMBOURG: "Luxembourg",
      NETHERLANDS: "Netherlands",
      SWITZERLAND: "Switzerland",
    },
    NORTHERN_EUROPE: {
      DENMARK: "Denmark",
      FINLAND: "Finland",
      IRELAND: "Ireland",
      NORWAY: "Norway",
      SWEDEN: "Sweden",
      UK: "United Kingdom",
    },
    SOUTHERN_EUROPE: {
      GREECE: "Greece",
      ITALY: "Italy",
      PORTUGAL: "Portugal",
      SPAIN: "Spain",
      SERBIA_MONTENEGRO: "Union of Serbia and Montenegro",
    },
    EASTERN_EUROPE: {
      CIS: "Commonwealth of Independent States",
      POLAND: "Poland",
      RUSSIA: "Russia",
    },
    AUSTRALASIA_PACIFIC: {
      AUSTRALIA: "Australia",
      GUAM: "Guam",
      NAURU: "Nauru",
      NEW_ZEALAND: "New Zealand",
      PAPUA_NEW_GUINEA: "Papua New Guinea",
    },
    AFRICA: {
      NIGERIA: "Nigeria",
      SOUTH_AFRICA: "South Africa",
    },
    OTHERS: "Others and Unspecified Residences",
    OVERSEAS_FILIPINO: "Overseas Filipino",
  };
  
  export default nationalityGroups;